### ISSUE TITLE
The Road to Quokka One

### ISSUE THREAD

**Issue by Happy-Ferret** [Anima-OS/Quokka#1]
### UI
- Retains most of the Australis design and extends it where necessary.
- Webkit-esque, rounded scrollbars.
- Retains "about:newtab" (no Activity Stream) and adds some customizability on top (Wallpapers).
- _Idea: Vertical tabs by default (optionally, traditional horizontal tabs) (could also host some social networking buttons, such as Facebook Messenger. See Opera Reborn)._
- Enables Social Sharing API frontend as part of the onboarding process.
- _Idea: Move "find bar" to top, for UX parity with Opera and Chrome._
- _Idea: Search for text/enter text into URL bar when user starts typing (see FindBar Tweak)._
- _Idea: Increase height of "find bar"._
- _Idea: Move "reload" button to the left of the URL bar._
  - Integrate/sync all UI changes with ``browser.uiCustomization.state``.
- [x] Add configurable search bar to preferences (see ``browser.search.widget.inNavBar``).
   - Implemented as of 57d93a6ab41c8fc186120423cbc1705f748e72f7
- Add blue "focus border" to text boxes (search, URL, etc) like in latest Firefox Nightly (59.x).
- Add "Download" button to video player (``toolkit/content/widgets/videocontrols.xml``), Opera style.
- Move https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly?redirectlocale=en-US&as=u&redirectslug=Keyboard+shortcuts&utm_source=inproduct to ``about:shortcuts``.
- http://blogs.opera.com/desktop/2017/09/convert-measurements-currencies-time-zones-opera-48/
- Import Bookmarks from more browsers (Vivaldi, Brave, Opera, Opera Reborn, Firefox).
- "De-Photonize" UI (remove ``if (AppConstants.MOZ_PHOTON_THEME)`` calls).
  - Alternatively, replace them with our own special flag for a new UI prototype, for now.
- Move "Share" button into URL bar.
- Allow regular elements to be added to the URL bar as page actions.
- Re-implement UI elements as Web Extensions/System Addons (first experiment: Bookmark button as a page action).
  - Check for performance regressions/startup delays when moving UI elements from the ``browser.xul`` structure into extensions. 
- Browser asset sharing (think graphics like the star icon needed for the bookmark UI) via ``moz-extension``? One global extension providing all the new UI assets? 

### Extensions
- Retains compatibility with "Legacy" extensions.
- Yellow "Legacy" labels replaced by blue "Privileged" ones, with a link explaining the differences between privileged SDK extensions and web extensions.
  - [ ] Text and style changes.
  - [ ] Link change.

### OS Support
Aiming for at least a working Windows and GNU/Linux release this cycle.

### Development methodology
- Development/Bugtracking/Planning hosted on Github.
- Moves as much as possible out of tree (via submodules).

## TODO

- [ ] Delete stale branches.
